language: go

go:
  - 1.12
  - 1.13

env:
  - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

script:
  - go test ./... -v -coverprofile=coverage.txt -covermode=atomic
  - go tool cover -func=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
